platform:
  - x64

environment:
  CYG_ARCH: x86_64
  CYG_ROOT: C:/cygwin64
  CYG_CACHE: C:/cygwin64/var/cache/setup
  CYG_SH: C:/cygwin64/bin/bash -lc
  CYG_INSTALL: C:/cygwin64/setup-x86_64.exe -q -P
  CYG_PATH: C:/cygwin64/bin/cygpath -u
  CYGWIN: "winsymlinks:native"
  OPAMYES: 1
  OPAMCOLORS: 1
  OPAMVERBOSE: 1
  BINDIR: 'C:\projects\vpnkit'

init:
  - git config --global core.symlinks true
  - git config --global core.autocrlf input
  - '%CYG_SH% "cygcheck -dc cygwin"'
  - '%CYG_INSTALL% "wget"'
  - '%CYG_SH% "wget rawgit.com/transcode-open/apt-cyg/master/apt-cyg"'
  - '%CYG_SH% "install apt-cyg /bin"'
  - '%CYG_SH% "apt-cyg install make autoconf automake gcc-core opam ocaml"'

cache:
  - '%CYG_CACHE%'
  - '%HOME%\.opam -> vpnkit.opam'

install:
  - cmd: echo Windows build is disabled until we can remove cygwin.

build_script:
  - "%CYG_SH% pwd"
  - '%CYG_SH% -c "ls /bin"'
  - '%CYG_SH% -c "ls /usr/bin"'
  - '%CYG_SH% -c "ls /usr/local/bin"'
  - '%CYG_SH% -c "echo ${APPVEYOR_BUILD_FOLDER}"'
  - '%CYG_SH% -c "/usr/bin/opam --version"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin ocaml"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin depends"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin build"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin artefacts"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin COMMIT"'
  - '%CYG_SH% -c "make -C ${APPVEYOR_BUILD_FOLDER} -f Makefile.darwin OSS-LICENSES"'

artifacts:
  - path: "vpnkit.exe"
  - path: "OSS-LICENSES"
  - path: "COMMIT"