version: 2
jobs:
  build:
    macos:
      xcode: "12.0"
    environment:
      OPAMYES: "1"
      OPAMJOBS: "2"
      MACOSX_DEPLOYMENT_TARGET: "10.10"
      OPAMVERBOSE: 1
      TERM: vt100
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkoutt

workflows:
  version: 2
  build-test-vpnkit:
    jobs:
      - build
